migrate(
  (app) => {
    const collection = new Collection({
      name: 'tabela_multas_nr28',
      type: 'base',
      // Referência oficial (Anexo I da NR-28) — pública, gerenciada só via migration.
      listRule: '',
      viewRule: '',
      createRule: null,
      updateRule: null,
      deleteRule: null,
      fields: [
        {
          name: 'faixa_funcionarios',
          type: 'select',
          required: true,
          values: [
            '01 a 10',
            '11 a 25',
            '26 a 50',
            '51 a 100',
            '101 a 250',
            '251 a 500',
            '501 a 1000',
            'Mais de 1000',
          ],
          maxSelect: 1,
        },
        // sem "required": um number com min:0 é tratado como "vazio" pelo validador
        // quando o valor é exatamente 0 (é o caso da primeira faixa, ordem 0).
        { name: 'faixa_ordem', type: 'number', min: 0, max: 7, onlyInt: true },
        { name: 'grau', type: 'number', required: true, min: 1, max: 4, onlyInt: true },
        { name: 'tipo', type: 'select', required: true, values: ['S', 'M'], maxSelect: 1 },
        { name: 'valor_min_ufir', type: 'number', required: true },
        { name: 'valor_max_ufir', type: 'number', required: true },
        { name: 'created', type: 'autodate', onCreate: true, onUpdate: false },
        { name: 'updated', type: 'autodate', onCreate: true, onUpdate: true },
      ],
      indexes: [
        'CREATE UNIQUE INDEX idx_tabela_multas_lookup ON tabela_multas_nr28 (faixa_ordem, grau, tipo)',
      ],
    })
    app.save(collection)

    // Seed — grade de gradação de multas do Anexo I da NR-28 (valores em UFIR).
    if (app.countRecords('tabela_multas_nr28') === 0) {
      const rows = [
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 630,
          valor_max_ufir: 729,
        },
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 378,
          valor_max_ufir: 428,
        },
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 1129,
          valor_max_ufir: 1393,
        },
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 676,
          valor_max_ufir: 839,
        },
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 1691,
          valor_max_ufir: 2091,
        },
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 1015,
          valor_max_ufir: 1254,
        },
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 2252,
          valor_max_ufir: 2792,
        },
        {
          faixa_ordem: 0,
          faixa_funcionarios: '01 a 10',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 1350,
          valor_max_ufir: 1680,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 730,
          valor_max_ufir: 830,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 429,
          valor_max_ufir: 498,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 1394,
          valor_max_ufir: 1664,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 840,
          valor_max_ufir: 1002,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 2092,
          valor_max_ufir: 2495,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 1255,
          valor_max_ufir: 1500,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 2793,
          valor_max_ufir: 3334,
        },
        {
          faixa_ordem: 1,
          faixa_funcionarios: '11 a 25',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 1681,
          valor_max_ufir: 1998,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 831,
          valor_max_ufir: 936,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 499,
          valor_max_ufir: 580,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 1665,
          valor_max_ufir: 1935,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 1003,
          valor_max_ufir: 1166,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 2496,
          valor_max_ufir: 2898,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 1501,
          valor_max_ufir: 1746,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 3335,
          valor_max_ufir: 3876,
        },
        {
          faixa_ordem: 2,
          faixa_funcionarios: '26 a 50',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 1999,
          valor_max_ufir: 2320,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 964,
          valor_max_ufir: 1104,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 581,
          valor_max_ufir: 662,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 1936,
          valor_max_ufir: 2200,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 1167,
          valor_max_ufir: 1324,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 2899,
          valor_max_ufir: 3302,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 1747,
          valor_max_ufir: 1986,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 3877,
          valor_max_ufir: 4418,
        },
        {
          faixa_ordem: 3,
          faixa_funcionarios: '51 a 100',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 2321,
          valor_max_ufir: 2648,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 1105,
          valor_max_ufir: 1241,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 663,
          valor_max_ufir: 744,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 2201,
          valor_max_ufir: 2471,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 1325,
          valor_max_ufir: 1482,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 3303,
          valor_max_ufir: 3718,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 1987,
          valor_max_ufir: 2225,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 4419,
          valor_max_ufir: 4948,
        },
        {
          faixa_ordem: 4,
          faixa_funcionarios: '101 a 250',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 2649,
          valor_max_ufir: 2976,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 1242,
          valor_max_ufir: 1374,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 745,
          valor_max_ufir: 826,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 2472,
          valor_max_ufir: 2748,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 1483,
          valor_max_ufir: 1646,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 3719,
          valor_max_ufir: 4121,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 2226,
          valor_max_ufir: 2471,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 4949,
          valor_max_ufir: 5490,
        },
        {
          faixa_ordem: 5,
          faixa_funcionarios: '251 a 500',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 2977,
          valor_max_ufir: 3297,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 1375,
          valor_max_ufir: 1507,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 827,
          valor_max_ufir: 906,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 2749,
          valor_max_ufir: 3020,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 1647,
          valor_max_ufir: 1810,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 4122,
          valor_max_ufir: 4525,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 2472,
          valor_max_ufir: 2717,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 5491,
          valor_max_ufir: 6033,
        },
        {
          faixa_ordem: 6,
          faixa_funcionarios: '501 a 1000',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 3298,
          valor_max_ufir: 3618,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 1,
          tipo: 'S',
          valor_min_ufir: 1508,
          valor_max_ufir: 1646,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 1,
          tipo: 'M',
          valor_min_ufir: 907,
          valor_max_ufir: 990,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 2,
          tipo: 'S',
          valor_min_ufir: 3021,
          valor_max_ufir: 3284,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 2,
          tipo: 'M',
          valor_min_ufir: 1811,
          valor_max_ufir: 1973,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 3,
          tipo: 'S',
          valor_min_ufir: 4526,
          valor_max_ufir: 4929,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 3,
          tipo: 'M',
          valor_min_ufir: 2718,
          valor_max_ufir: 2957,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 4,
          tipo: 'S',
          valor_min_ufir: 6034,
          valor_max_ufir: 6304,
        },
        {
          faixa_ordem: 7,
          faixa_funcionarios: 'Mais de 1000',
          grau: 4,
          tipo: 'M',
          valor_min_ufir: 3619,
          valor_max_ufir: 3782,
        },
      ]
      for (const r of rows) {
        const rec = new Record(collection)
        rec.set('faixa_funcionarios', r.faixa_funcionarios)
        rec.set('faixa_ordem', r.faixa_ordem)
        rec.set('grau', r.grau)
        rec.set('tipo', r.tipo)
        rec.set('valor_min_ufir', r.valor_min_ufir)
        rec.set('valor_max_ufir', r.valor_max_ufir)
        app.save(rec)
      }
    }
  },
  (app) => {
    app.delete(app.findCollectionByNameOrId('tabela_multas_nr28'))
  },
)
